version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /app/dico-darmanin
    volumes:
      - ./:/app
    depends_on:
      - database
    networks:
      - app-network
      - npm-network

  database:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
  npm-network:
    external: true

volumes:
  db-data:
    driver: local
